### ISSUE TITLE
Display a dash (—) in case of null value

### ISSUE THREAD

**Issue by FaridAghili** [dpsoft-official/nova-persian-date#2]
به نظرم بهتره فارسی بنویسم!

![image](https://user-images.githubusercontent.com/8607021/119906122-d8cdd380-bf62-11eb-9acd-aef53dc33d0e.png)

همونطور که در تصویر می‌بینید، در صورتی که مقدار فیلد برابر با نال باشه، هیچ چیزی نمایش داده نمی‌شه، اما فیلدهای پیشفرض نوا برای مقدار نال یه خط تیره نشون می‌دن.

اگه امکانش هست این رو اضافه کنید تا همخوانی بیشتری با فیلدهای پیشفرض داشته باشه.
ممنون

**Comment by FaridAghili** [comment]
https://github.com/dpsoft-official/nova-persian-date/blob/ff54e9b9225713b71be276e2525f5dbb44da820e/resources/js/components/IndexField.vue#L12-L14

فکر می‌کنم مربوط به این قسمت باشه

```diff
persianDate() {
    if (this.field.value) {
        return jMoment(this.field.value).format(this.field.format || 'jYYYY/jMM/jDD');
    }

+    return '—';
}
```

**Comment by SadeghPM** [comment]
تشکر
اضافه میشه👍
