### ISSUE TITLE
مشکل در نمایش

### ISSUE THREAD

**Issue by payamt007** [dpsoft-official/nova-persian-date#3]
ضمن تشکر از شما بابت این پکیج خوب. یه مشکلی در نمایش تاریخ فارسی وجود داره که مثدار فیلد زیر عنوان ستون قرار نمیگیره. اگه درستش کنید خیلی ممنون میشم
![github](https://user-images.githubusercontent.com/57144856/132251295-18f8c2c6-9325-4ec8-8725-ce294a6bae94.png)

**Comment by FaridAghili** [comment]
@payamt007 پیشنهاد می‌کنم از پکیج زیر جهت راست به چپ کردن نوا استفاده کنید:
https://github.com/pishran/nova-rtl-theme
